/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.webFontIssue.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFontScopeProvider extends DelegatingScopeProvider {
}
