/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.webFontIssue.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.webFontIssue.parser.antlr.internal.InternalFontParser;
import org.xtext.example.webFontIssue.services.FontGrammarAccess;

public class FontParser extends AbstractAntlrParser {

	@Inject
	private FontGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFontParser createParser(XtextTokenStream stream) {
		return new InternalFontParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public FontGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FontGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
