/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.webFontIssue


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FontStandaloneSetup extends FontStandaloneSetupGenerated {

	def static void doSetup() {
		new FontStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
